// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyDThpBCWqc2qI2sloz7i44cuU4Zj38rM',
    appId: '1:369668101912:web:891a8ff7ea4e880c98f06d',
    messagingSenderId: '369668101912',
    projectId: 'dirty-roots',
    authDomain: 'dirty-roots.firebaseapp.com',
    storageBucket: 'dirty-roots.appspot.com',
    measurementId: 'G-R1Q442CYM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWsI0gQzD3IHGjJj1ZSyz6S5oYd9j6_HY',
    appId: '1:369668101912:android:d9e6f79dd40b6e3798f06d',
    messagingSenderId: '369668101912',
    projectId: 'dirty-roots',
    storageBucket: 'dirty-roots.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7HHnGeHQB_cH3RuIhte74qXFCOhB1Yi4',
    appId: '1:369668101912:ios:8ca03213bbcb25e298f06d',
    messagingSenderId: '369668101912',
    projectId: 'dirty-roots',
    storageBucket: 'dirty-roots.appspot.com',
    iosBundleId: 'com.example.dirtyRoots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7HHnGeHQB_cH3RuIhte74qXFCOhB1Yi4',
    appId: '1:369668101912:ios:8ca03213bbcb25e298f06d',
    messagingSenderId: '369668101912',
    projectId: 'dirty-roots',
    storageBucket: 'dirty-roots.appspot.com',
    iosBundleId: 'com.example.dirtyRoots',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyDThpBCWqc2qI2sloz7i44cuU4Zj38rM',
    appId: '1:369668101912:web:9a23cdece01a7b0b98f06d',
    messagingSenderId: '369668101912',
    projectId: 'dirty-roots',
    authDomain: 'dirty-roots.firebaseapp.com',
    storageBucket: 'dirty-roots.appspot.com',
    measurementId: 'G-4WXNT0XYVS',
  );
}
